### ISSUE TITLE
how to serieslize ForeignKey default?

### ISSUE THREAD

**Issue by eromoe** [marshmallow-code/marshmallow-sqlalchemy#118] opened 2017-09-12 05:54 UTC
I have a model with below field:
```
    corpus_id = Column(Integer, ForeignKey('corpus.id', ondelete='CASCADE'))
    corpus = relationship('Corpus', backref=backref('documents', order_by=id, cascade='all, delete-orphan'), foreign_keys=corpus_id)
```

After serieslization, it became 
```
{
    "corpus": 1,
    "created": "2017-09-12T05:50:07+00:00",
    "id": 1,
    "text": "text",
    "title": "doc1",
}
```

I want `corpus_id` , not `corpus`

**Comment by timster** [comment] 2017-09-14 10:50
Add `include_fk = True` to your schema's `Meta` class.

**Comment by eromoe** [comment] 2017-09-15 08:29
But  `"corpus": 1`  still existed.  I have to exclude it.  And have to write such code to many other schema.
This default behave is strange for me .  

Why not show `corpus_id ` instead of `corpus` default  ?

**Comment by yuvadm** [comment] 2018-03-22 13:06
Probably a duplicate of #98

**Comment by AbdealiLoKo** [comment] 2018-12-04 18:13
Closing as duplicate

**Closed as completed by AbdealiLoKo** 2018-12-04 18:13 UTC
